services:
  dt4h-preprocessing:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - /opt:/opt
      - ../CogStack-NiFi/data:/cogstack_data  # mount the shared data dir

networks:
  default:
    name: cogstack-net
    external: true
